// <auto-generated />
using System;
using LakbayGameApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LakbayGameApi.Migrations
{
    [DbContext(typeof(LakbayGameDbContext))]
    [Migration("20260719095214_SeedNewData")]
    partial class SeedNewData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LakbayGameApi.Models.DailyRewardRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int");

                    b.Property<DateTime>("RewardDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyRewards");
                });

            modelBuilder.Entity("LakbayGameApi.Models.LessonActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lesson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalActivities")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LessonActivities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = "Day 1",
                            Lesson = "Lesson 1",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 2,
                            Day = "Day 2",
                            Lesson = "Lesson 1",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 3,
                            Day = "Day 3",
                            Lesson = "Lesson 1",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 4,
                            Day = "Day 4",
                            Lesson = "Lesson 1",
                            TotalActivities = 1
                        },
                        new
                        {
                            Id = 5,
                            Day = "Day 1",
                            Lesson = "Lesson 2",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 6,
                            Day = "Day 2",
                            Lesson = "Lesson 2",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 7,
                            Day = "Day 3",
                            Lesson = "Lesson 2",
                            TotalActivities = 2
                        },
                        new
                        {
                            Id = 8,
                            Day = "Day 4",
                            Lesson = "Lesson 2",
                            TotalActivities = 1
                        },
                        new
                        {
                            Id = 9,
                            Day = "Day 1",
                            Lesson = "Lesson 3",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 10,
                            Day = "Day 2",
                            Lesson = "Lesson 3",
                            TotalActivities = 2
                        },
                        new
                        {
                            Id = 11,
                            Day = "Day 3",
                            Lesson = "Lesson 3",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 12,
                            Day = "Day 4",
                            Lesson = "Lesson 3",
                            TotalActivities = 2
                        },
                        new
                        {
                            Id = 13,
                            Day = "Day 1",
                            Lesson = "Lesson 4",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 14,
                            Day = "Day 2",
                            Lesson = "Lesson 4",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 15,
                            Day = "Day 3",
                            Lesson = "Lesson 4",
                            TotalActivities = 3
                        },
                        new
                        {
                            Id = 16,
                            Day = "Day 4",
                            Lesson = "Lesson 4",
                            TotalActivities = 1
                        });
                });

            modelBuilder.Entity("LakbayGameApi.Models.Points", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Act")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountedPoints")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lesson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("LakbayGameApi.Models.TotalPoints", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TotalCountedPoints")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TotalPoints");
                });

            modelBuilder.Entity("LakbayGameApi.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
